import turtle
turtle.showturtle()
turtle.penup()#十字
turtle.goto(-100,0)
turtle.pendown()
turtle.goto(100,0)
turtle.penup()
turtle.goto(0,100)
turtle.pendown()
turtle.goto(0,-100)
turtle.penup()
turtle.goto(200,0)#五角星
turtle.pendown()
turtle.write("五角星")
turtle.forward(100)
turtle.right(144)
turtle.color("red")
turtle.forward(100)
turtle.right(144)
turtle.color("blue")
turtle.forward(100)
turtle.right(144)
turtle.color("green")
turtle.forward(100)
turtle.right(144)
turtle.color("purple")
turtle.forward(100)
turtle.right(144)


